import fs from "fs";
import path from "path";
import matter from "gray-matter";
import Head from "next/head";
import Post from "../components/Post";
import {sortByDate} from '../utils'

// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

export default function Home({ posts }) {
  // console.log(posts);
  return (
    <div>
      <Head>
        <title>Dev Blog</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className="posts">
        {posts.map((post, index) => (
          <div key={index}>
            <Post post={post} />
          </div>
        ))}
      </div>
    </div>
  );
}

export async function getStaticProps() {
  //Get files from the posts dir
  const files = fs.readdirSync(path.join("posts"));

  //Get slug and frontmatter from posts
  const posts = files.map((filename) => {
    //create slug
    const slug = filename.replace(".md", "");
    //Get frontmatter
    const markdownWithMeta = fs.readFileSync(
      path.join("posts", filename),
      "utf-8"
    );
    const { data: frontmatter } = matter(markdownWithMeta);
    return {
      slug,
      frontmatter,
    };
  });
  console.log(posts);
  return {
    props: {
      posts: posts.sort(sortByDate),
    },
  };
}
